

: STAR 42.0 EMIT ;
: OTHERDEF 42.0 PRINTLN ;
: STARS 0.0 DO STAR LOOP ;



"Test String   " PRINTLN OTHERDEF STAR 43.0 DUP EMIT PRINTLN 0.0 IF 40.0 STARS ELSE 0.0 IF "No!" PRINTLN ELSE "here!" PRINTLN THEN THEN END
